---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mattermost-db-postgresql
  namespace: mattermost
spec:
  encryptedData:
    password: AgBx+M8nn7a3dKvay4p9fwvu5O6+1J69oth3b7EjtH+o6qD8DwG++IIqH2ao5zUDNjm0NN4jD8Dv1RHNTv07n9sysuadEUn6rnu8KF3h4HmJJQDrk7LCsZKqiMG+cLQJhcdq8S9Jr9oTF1kSSWzR7FeqPfEGxHEgrid3cSKjwQsgH2qc8eajjAcnlN5B3PUTexYBsqGFeuymLXe31kBARQex0ex76ndYwhM1RSzwj78nZ5Bc3jIFJSIrnj+8pjPiGz8CUF7VZzpLOipKjknn0nUVnCdBR8ei4CnvjzpuOajD7bRArHZ0gfyi5RJGcAliYkwzCQXUDh3HHVY77JH7BPu7jLeoxqZMZOYuDfZ7l8+kyrsV+fMPSOaVKreEwpvYbVh2PnF2fMbbOm5kp99w5fxO2sACU0uViqIJKLDsoAFxjrtE6UL1MPO24bGPSuHTzDVjnw+omzQwb4lnuNhImk9insTHiUmjcko/1ExB5/RG2ka36so5fxO36iOaWTNZcSQfV+4o4NJbqPfQhMntc0RKRgYnwD2tAtjgkxJpoYORkQfQ+8sgIKQw9PA3uvsstgyVttvTzJDv4i4BTxjMI3H1OoGtufOm657j9NFktz07dcbhhACvIGCLiLJLduswiMFmvI9CRRWwwPEhtOAkDfTv8EKsnafvUtev4fLLTNR2yPt3JsiEFt8CLBdCWWxVWsnz/iWHVuI4cGuyeg==
    postgres-password: AgAe48r/Cx9qH48lEOAO+iqd04jNa0Le9vqyEgQ1NkNb23XeCdXFF2IVzpefctN59milLxY4Ljvo0ctSjxnniU3LpB7wQyjIMmoFTMawqoXGZ1kGTqvgFda/ePXPwc0PAcO/EgcVh8RiVy+cbLGvZiNImjwNJg4vwZploZ1G8yHsCbp+jMN8rjTjeFPNkGX1cLiH9sBmpLpokUVpdMCmdQAk0vB0AKEWy2ky5RPWpHDsyYRxLehXtSw3KViMh19sZTVZ1lGi8NucP+7XzaBSuG84Q/3DrgCzr5uv491T1baZ5mcF4wB4WuCRbV96o4ZjTJp/8UGbjFSngyJHuL0GLOhnQxgjgLFTmfu0LvLFMN5NL2RtL4mSey94Z97HrPHfCI16gWfC1t9EQPT5epZ4Y0n2smg1iF7eNTZ7KfJBLHLFsIri0Yoo3PzoXnN6in8PK99lQtO+4GZUhmvFHqwCaEZAsAzlsLDxLzUl2RdZIy7AgYv4qYpSpP1b1NHxiSSWT1f9D+rsduoEhhiRNJdbovW4LnG2KxPC76cCiqD8GLVkb4DnGk45ztfbe/cSd7hH6DW9MWA9k9FSsfsfLG7ROGg12XC5IS3+1w1oR3s/LJsWQEUk+y4EWDomQnCzzMNDKDWvKGg8+/omG+rIFh7KwiTY342Dw7jTV6CSx3XXomdP0aq5DgeRZK0AdN+q9aPQY/RVPpZHiDmc0YXrmg==
  template:
    metadata:
      name: mattermost-db-postgresql
      namespace: mattermost
