---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mattermost-db-credentials
  namespace: mattermost
spec:
  encryptedData:
    DB_CONNECTION_STRING: AgBnp8YQIiwzAt9rWvUO/3heU7e1aESno+eJgV5iJpuwtC0FFfQQ5hx6lDEW5x/eG4jSnYan25tw8vT/Jt0UoUv6fD/iElt4aetixrtinz0XBc3jMd9jQjti3iFsN8ykQ30k+f7Dh0ZQD+92rnGasEuui2GSuMosrmcs7KtulK9nmxuTOjFHBmWyBS6m4XEinnbMryQEUGu3MbtciHAyKthxnd++5UZDwtt0qsnxfn4OPA8ZUvNC9f5aZMmsII1zGJaU6XiOdb2XnI2pAixhPFVwU7UoUGq4vXFgLDhR1e6cEuNm+oA/+VBb/PndLJM/F1Hi4gSGKEEUhM25vTCzLuJ5oAD8jmH4c9BPB6+fah6iccAewiOZdDqdQ7BDKLlS11WIlsdFqPNDv+z/tZ8/Un0eWAaqmWw56Oy+6zBzGloIW2m9OGxA2YA5i4SSUiYSUqEcBLh6bBkEbTJfXxvK1jv1naR2KKlXPvpi9jWghOI+gZ6j5aFX7n83mnKdF4MXzG/AX/9Iwd4NVkkGPXpyqpQSA2CDdF3PktnH6H/B1FtqXx4T62dC3lIPCDmlka2qbA5LTcDUA6xfP+xPkieEIFwLXnsZbuGUh6HRAqop8QBPz0sIUSNLmKM42KbUHngVn2LUAu8XDxc5VeyIQZ5a7jRGr2j/PqiKhbBSS/jnEyCE0YZXf+rXjRIECwDY4lDFU63XCup8OR1Z9LYx5PRCvRgom7mOQL4RX1zv74g31vKJEZewDEtmfxIwjiXaC3tZcgUbaSJOpRf9g8lnvYLPv/L0UVUAMAtJAygxqr1racuMNSQbpgLktnQmaPSXL8wn1DH1WSC6V4JtxHuxejHLIBJbXO3q
  template:
    metadata:
      name: mattermost-db-credentials
      namespace: mattermost
