---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mattermost-minio-credentials
  namespace: mattermost
spec:
  encryptedData:
    accesskey: AgAUX5Yum+MO5CiZGExbUjiQ+gHiiHs2HprgorfrBmaAzDucnoA3HcZzRvDcnvOj19EaZL+D0GHZnTQonsIYKWC2extsetHHRvLypFydxXkYwhERsdHWke5qlcue1QU6MvHxun179KlU+qCjGdO/052fNh/P8OfX2pc01n2g7Yotd9koqydeqLyhfsv7gQi7tcAJgvqxJsH+bhpzZpMDLOZv07R+pbJmAK4pANAmPtlktrY0qJZtBzwS9Lf31l3LZHmVe4ojQLRRjSzEZYVgZGx/+dQc+gIGDw2gbZLkbR6Yll1FKwd+zJrdhhzYqK9js1b3hhqKSYpG3OiQGve+24u9Z7CXN0zboy2DGtszoOVZKZABcmfEKCcw0MrvUy9NEoUL7nTUdULJ9SqpmQHL2dHu5PRTj/75ukoNZEY57M3Bjlh/RxWqZ1T0GSs55zVWpPJwSEH+rNRkQ0yDTweC77U+GZohzTCR2ERdp6Zx+FVzRnkxIhpiNG4RlZ3k24oKjZetxDaYO5q9aqQGEO01M8IlCDH9cVODuBjKY4WObpfzx+cZBG9/DAz0Wy5M648hQIbCEeYOPLrnHkaw1w0k+K9wIV6lWjkcF9YsnOMXv4bHAXBRzoU6FG3z8s0KWveZvFjgZsrlxITvwMWLiTMhqtYhu3GNP7JqjP95ndT7BycNu7R5E29wIwcFF80pHKsqh79AZ+4ouL4Xar4+h3yaB7Oo
    secretkey: AgCwhOObB4ubN8VPJHf4beeloo+mHfR/OIEu3AukFKj1/+Vc3NaUFT9/3HxRXzE+T/j22g3oAz8ZkNhfdAJo7BAtYenq3d9dVVLp/g6E5onjg2tLcJWYtFeqhQMa6nWArIeb/fGCUVe/XZALVcBpPU/uSw/Je0WY4Z3L56dV7SEbdmxHKxkA1LC/MYbuXjFulDxinbFiB+BWoD0slje9tAsjlu+YV2amPr73c2Rv8byZekOZqSK27ned0tkKKOVHAS9eXPzzC4/Ic2MEjD6Anlg8HQESXVWzRcFIHU83MIjAl9oDE16qeO929FeB4pS1lXNFq9/yvrkw6R13oMDT3xc59jyshVjbHuZUHMj5TlqCFzU+V788UJIkdIFCrCHfLZbXaVPQxGEfyFSq6z6IjoMpzbxfcVBf26L6b6sRejxx2fXt+/YrI4/S3tb2h4/03v8gHgMBNNG7PawpTch3G1zCXHllb4noCEXYzlA5k4KOuz6ft6jX/jxW02eovBWSBTtAysrJF/O4A2Zzv8FbRSgUTH66ym8Yuj6uc77HgWIc8DeCXVSj02y5SN4eQAwHalZVdyEHdxFTGSyS7TAt+gxTkVrpwDRM6nX+PhkWyImxVeu+azOsoBAzeGCKQ/llHJbrWjfZeXkJpiL9cqTk/b6NbuTxT32nnjmt+9NGSlOQT8AxsA22VPB//hUZh1/W2h6/R6PKUdEQZ963M9c=
  template:
    metadata:
      name: mattermost-minio-credentials
      namespace: mattermost
